### ISSUE TITLE
BUG：变量替换错误

### ISSUE THREAD

**Issue by KangLin** [hustlei/QssStylesheetEditor#15]
$text = #222;
$textDisable = #B3B3B3;
$background = #FFFFFF;

QWidget
{
    color: $text;
    background-color: $background;
}
QWidget:disabled
{
    color: $textDisable;
}

错误：
QWidget:disabled
{
    color: #222Disable;
}

错误原因：第一个变量替换时，把后面一个变量的前面部分替换了。
修改建议：模式匹配时在变量后加上" [ ]*;  "

**Comment by hustlei** [comment]
好的，谢谢

> $text = #222;
> $textDisable = #B3B3B3;
> $background = #FFFFFF;
> 
> QWidget
> {
> color: $text;
> background-color: $background;
> }
> QWidget:disabled
> {
> color: $textDisable;
> }
> 
> 错误：
> QWidget:disabled
> {
> color: #222Disable;
> }
> 
> 错误原因：第一个变量替换时，把后面一个变量的前面部分替换了。
> 修改建议：模式匹配时在变量后加上" [ ]*; "

ok，谢谢

**Comment by hustlei** [comment]
已修改
