### ISSUE TITLE
Start bug.

### ISSUE THREAD

**Issue by thegame4craft** [hustlei/QssStylesheetEditor#29]

**Comment by thegame4craft** [comment]
i have downloaded the latest version (1.6) and unzipped an followed the usage.md. but at the last step I getting following error:
`  File "qsseditor.pyw", line 4
SyntaxError: Non-UTF-8 code starting with '\xa1' in file qsseditor.pyw on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`
I use python3.8 with venv

**Comment by hustlei** [comment]
thx, it will be fixed
