### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by dry11orange** [hustlei/QssStylesheetEditor#6]
在文件保存的时候,自动生成qss文件
---
- 这样在使用的时候,就不需每次手动生成qss了

**Comment by hustlei** [comment]
好的，我后期增加一个设置选项，可以在每次保存的时候自动生成qss文件

**Comment by hustlei** [comment]
已增加：
1. 每次保存会自动导出qss文件，文件名与xxx.qsst相同，后缀不同
2. 如果xxx.qss文件存在，保存的时候会将xxx.qss备份在xxx.qss.backup，然后再导出
3. 默认不开启该功能，在设置中勾选了Export qss When save qsst才会自动导出
