### ISSUE TITLE
ModuleNotFoundError: splash.preimport

### ISSUE THREAD

**Issue by cnrdzn** [hustlei/QssStylesheetEditor#7]
Hey hustlei,

I Installed all dependencies. when i try to run app.py getting this error.

```
D:\Software\QssStylesheetEditor-master\build\lib>app.py
Traceback (most recent call last):
  File "D:\Software\QssStylesheetEditor-master\build\lib\app.py", line 13, in <module>
    from splash import SplashScreen
  File "D:\Software\QssStylesheetEditor-master\build\lib\splash\__init__.py", line 9, in <module>
    from .splash import SplashScreen
  File "D:\Software\QssStylesheetEditor-master\build\lib\splash\splash.py", line 11, in <module>
    from .preimport import preload
ModuleNotFoundError: No module named 'splash.preimport'
```

Python 3.8.0
Windows 10

**Comment by hustlei** [comment]
if you installed all dependencies, you can try to run the app.py in src folder.  

> additionally why your app.py is in build\lib folder

**Comment by cnrdzn** [comment]
Yes, i tried **src\app.py**

> Alternatively, you can download the last source and install the 'preimport' dependency, and try to run again.

getting same error.

**Comment by hustlei** [comment]
Could you update the source by `git clone https://github.com/hustlei/QssStylesheetEditor.git`, and try again? I have make same changes.

> If the error is still exist, could you email the source on your machine and the error infomation to <hustlei@sina.cn>. thanks.

**Comment by cnrdzn** [comment]
Thanks. issue fixed !
